'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _ioredisUtils = require('ioredis-utils');

const descriptors = [{
  descriptor: {
    file: 'hsetifeq.lua',
    name: 'hsetifeq',
    ext: '.lua'
  },
  data: '-- name:  hsetifeq\n-- keys:  key field value\nlocal value = unpack(redis.call("HMGET", KEYS[1], KEYS[2]))\nlocal check = KEYS[3]\nif value == check then\n  return redis.call("HMSET", KEYS[1], unpack(ARGV))\nelse\n  return nil\nend\n',
  params: new Map([["name", "hsetifeq"], ["keys", ["key", "field", "value"]]])
}];
// Auto-Generated by build-lua script in utils folder
// These are pre-compiled lua script descriptors which can be loaded
// into


function addDefaultScriptsToRedis(redis) {
  return _ioredisUtils.lua.addScriptsToRedis(redis, descriptors);
}

exports.default = addDefaultScriptsToRedis;